import type {
  FormElementOrList,
  FormObject,
  FormStep,
} from "@/form-builder/form-types"

export const templates: FormObject[] = [
  {
    id: "template-signup",
    title: "Signup Form",
    isMS: false,
    formElements: [
      {
        id: "signup-heading",
        name: "Heading",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Sign Up",
      },
      {
        id: "signup-paragraph",
        name: "Paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "You need an account to get started",
      },
      {
        id: "signup-name",
        name: "name",
        fieldType: "Input",
        type: "text",
        label: "Your Name",
        placeholder: "Enter your Name",
        required: true,
      },
      {
        id: "signup-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email",
        placeholder: "Enter your Email",
        required: true,
      },
      [
        {
          id: "signup-password",
          name: "password",
          fieldType: "Password",
          type: "password",
          label: "Password",
          placeholder: "Password",
          required: true,
        },
        {
          id: "signup-password-confirm",
          name: "confirm-password",
          fieldType: "Password",
          type: "password",
          label: "Confirm Password",
          placeholder: "Confirm Password",
          required: true,
        },
      ],
      {
        id: "separator",
        fieldType: "Separator",
        label: "OR",
      },
      {
        id: "signup-social-media-buttons",
        name: "social-media-buttons",
        fieldType: "SocialMediaButtons",
        links: ["google", "github"],
        layout: "row",
      },
      {
        id: "signup-agree",
        name: "agree",
        fieldType: "Checkbox",
        label: "I agree to the terms and conditions",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-credit-card",
    title: "Credit Card Form",
    isMS: false,
    formElements: [
      {
        id: "credit-card-heading",
        name: "heading",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Credit Card",
      },
      {
        id: "credit-card-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Enter your credit card details example",
      },
      {
        id: "credit-card-fullname",
        name: "fullname",
        fieldType: "Input",
        type: "text",
        label: "Full Name",
        placeholder: "Enter your Full Name",
        required: true,
        width: "md:col-span-3",
      },
      {
        id: "credit-card-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email",
        placeholder: "Enter your Email",
        required: true,
        width: "md:col-span-3",
      },
      {
        id: "credit-card-number",
        name: "number",
        label: "Credit Card Number (IBAN)",
        fieldType: "Input",
        type: "text",
        placeholder: "Enter your Credit Card Number",
      },
      {
        id: "credit-card-expiry-date",
        name: "expiry-date",
        fieldType: "Input",
        placeholder: "Expiry Date",
        label: "Expiry Date",
        type: "text",
        required: true,
        width: "md:col-span-3",
      },
      {
        id: "credit-card-cvv",
        name: "cvv",
        fieldType: "Input",
        placeholder: "CVV",
        label: "CVV",
        type: "text",
        required: true,
        width: "md:col-span-3",
      },
      {
        id: "credit-card-agree",
        name: "agree",
        fieldType: "Checkbox",
        label: "I agree to the terms and conditions",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-login",
    title: "Login Form",
    isMS: false,
    formElements: [
      {
        id: "login-heading",
        name: "login",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Login",
      },
      {
        id: "sign-up-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Login to create an account",
      },
      {
        id: "login-email",
        name: "email",
        label: "Email",
        fieldType: "Input",
        type: "email",
        placeholder: "Enter your Email",
      },
      {
        id: "login-password",
        name: "password",
        fieldType: "Password",
        placeholder: "Password",
        label: "Password",
        type: "password",
        required: true,
      },
      {
        id: "separator",
        fieldType: "Separator",
        label: "OR",
      },
      {
        id: "login-social-media-buttons",
        name: "social-media-buttons",
        fieldType: "SocialMediaButtons",
        links: ["google", "discord"],
        layout: "row",
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-employee-onboarding",
    title: "Employee Onboarding",
    isMS: true,
    formElements: [
      {
        id: "onboarding-step-1",
        stepFields: [
          {
            id: "onboarding-personal-heading",
            name: "heading-personal",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Personal Information",
          },
          {
            id: "onboarding-personal-paragraph",
            name: "paragraph-personal",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Please provide your personal details for our records",
          },

          {
            id: "onboarding-first-name",
            name: "firstName",
            fieldType: "Input",
            type: "text",
            label: "First Name",
            placeholder: "Enter your first name",
            required: true,
            width: "md:col-span-3",
          },
          {
            id: "onboarding-last-name",
            name: "lastName",
            fieldType: "Input",
            type: "text",
            label: "Last Name",
            placeholder: "Enter your last name",
            required: true,
            width: "md:col-span-3",
          },
          {
            id: "onboarding-email",
            name: "email",
            fieldType: "Input",
            type: "email",
            label: "Email Address",
            placeholder: "Enter your email address",
            required: true,
          },
          {
            id: "onboarding-phone",
            name: "phone",
            fieldType: "Input",
            type: "tel",
            label: "Phone Number",
            placeholder: "Enter your phone number",
            required: true,
            width: "md:col-span-3",
          },
          {
            id: "onboarding-date-of-birth",
            name: "dateOfBirth",
            fieldType: "Input",
            type: "date",
            label: "Date of Birth",
            required: true,
            width: "md:col-span-3",
          },
          {
            id: "onboarding-address",
            name: "address",
            fieldType: "Textarea",
            label: "Home Address",
            placeholder: "Enter your complete home address",
            required: true,
          },
        ],
      },
      {
        id: "onboarding-step-2",
        stepFields: [
          {
            id: "onboarding-employment-heading",
            name: "heading-employment",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Employment Details",
          },
          {
            id: "onboarding-employment-paragraph",
            name: "paragraph-employment",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Please provide your employment information",
          },
          {
            id: "onboarding-position",
            name: "position",
            fieldType: "Input",
            type: "text",
            label: "Job Title/Position",
            placeholder: "Enter your job title",
            required: true,
          },
          [
            {
              id: "onboarding-department",
              name: "department",
              fieldType: "Select",
              label: "Department",
              placeholder: "Select your department",
              required: true,
              options: [
                { label: "Engineering", value: "engineering" },
                { label: "Marketing", value: "marketing" },
                { label: "Sales", value: "sales" },
                { label: "Human Resources", value: "hr" },
                { label: "Finance", value: "finance" },
                { label: "Operations", value: "operations" },
              ],
            },
            {
              id: "onboarding-start-date",
              name: "startDate",
              fieldType: "Input",
              type: "date",
              label: "Start Date",
              required: true,
            },
          ],
          {
            id: "onboarding-employment-type",
            name: "employmentType",
            fieldType: "RadioGroup",
            label: "Employment Type",
            required: true,
            options: [
              { label: "Full-time", value: "fulltime" },
              { label: "Part-time", value: "parttime" },
              { label: "Contract", value: "contract" },
              { label: "Intern", value: "intern" },
            ],
          },
          {
            id: "onboarding-manager",
            name: "manager",
            fieldType: "Input",
            type: "text",
            label: "Direct Manager",
            placeholder: "Enter your direct manager's name",
            required: true,
          },
        ],
      },
      {
        id: "onboarding-step-3",
        stepFields: [
          {
            id: "onboarding-emergency-heading",
            name: "heading-emergency",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Emergency Contact",
          },
          {
            id: "onboarding-emergency-paragraph",
            name: "paragraph-emergency",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Please provide emergency contact information",
          },
          [
            {
              id: "onboarding-emergency-name",
              name: "emergencyContactName",
              fieldType: "Input",
              type: "text",
              label: "Emergency Contact Name",
              placeholder: "Enter contact's full name",
              required: true,
            },
            {
              id: "onboarding-emergency-relationship",
              name: "emergencyContactRelationship",
              fieldType: "Select",
              label: "Relationship",
              placeholder: "Select relationship",
              required: true,
              options: [
                { label: "Spouse", value: "spouse" },
                { label: "Parent", value: "parent" },
                { label: "Sibling", value: "sibling" },
                { label: "Child", value: "child" },
                { label: "Friend", value: "friend" },
                { label: "Other", value: "other" },
              ],
            },
          ],
          [
            {
              id: "onboarding-emergency-phone",
              name: "emergencyContactPhone",
              fieldType: "Input",
              type: "tel",
              label: "Emergency Contact Phone",
              placeholder: "Enter contact's phone number",
              required: true,
            },
            {
              id: "onboarding-emergency-email",
              name: "emergencyContactEmail",
              fieldType: "Input",
              type: "email",
              label: "Emergency Contact Email",
              placeholder: "Enter contact's email address",
            },
          ],
        ],
      },
      {
        id: "onboarding-step-4",
        stepFields: [
          {
            id: "onboarding-documents-heading",
            name: "heading-documents",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Documents & Agreements",
          },
          {
            id: "onboarding-documents-paragraph",
            name: "paragraph-documents",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Please upload required documents and review agreements",
          },
          {
            id: "onboarding-resume",
            name: "resume",
            fieldType: "FileUpload",
            label: "Resume/CV",
            placeholder: "Upload your resume (PDF, DOC, DOCX)",
            accept: "application/pdf, application/doc, application/docx",
            required: true,
          },
          {
            id: "onboarding-id-document",
            name: "idDocument",
            fieldType: "FileUpload",
            label: "Government ID",
            placeholder: "Upload a copy of your government ID (PDF, JPG, PNG)",
            accept: "application/pdf, image/jpeg, image/png",
            required: true,
          },
          {
            id: "onboarding-separator",
            fieldType: "Separator",
            label: "Agreements",
          },
          {
            id: "onboarding-handbook",
            name: "handbookAgreement",
            fieldType: "Checkbox",
            label: "I have read and agree to the Employee Handbook",
            required: true,
          },
          {
            id: "onboarding-confidentiality",
            name: "confidentialityAgreement",
            fieldType: "Checkbox",
            label: "I agree to the Confidentiality Agreement",
            required: true,
          },
          {
            id: "onboarding-code-of-conduct",
            name: "codeOfConductAgreement",
            fieldType: "Checkbox",
            label: "I agree to abide by the Company Code of Conduct",
            required: true,
          },
          {
            id: "onboarding-additional-notes",
            name: "additionalNotes",
            fieldType: "Textarea",
            label: "Additional Notes or Questions",
            placeholder:
              "Any additional information or questions you'd like to share...",
          },
        ],
      },
    ] as FormStep[],
  } as FormObject,
  {
    id: "template-feedback-form",
    title: "Feedback Form",
    isMS: false,
    formElements: [
      {
        id: "feedback-heading",
        name: "feedback",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Feedback Form",
      },
      {
        id: "feedback-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Please provide your feedback",
      },
      {
        id: "feedback-comment",
        name: "comment",
        fieldType: "Textarea",
        placeholder: "Share your feedback",
        label: "Feedback Comment",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-waitlist",
    title: "Waitlist",
    isMS: false,
    formElements: [
      {
        id: "waitlist-heading",
        name: "heading",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Waitlist",
      },
      {
        id: "waitlist-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Join our waitlist to get early access",
      },
      {
        id: "waitlist-email",
        name: "email",
        label: "Your Email",
        fieldType: "Input",
        type: "email",
        placeholder: "Enter your Email",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-contact-us",
    title: "Contact Us",
    isMS: false,
    formElements: [
      {
        id: "contact-heading",
        name: "heading",
        fieldType: "Text",
        variant: "H2",
        static: true,
        content: "Contact us",
      },
      {
        id: "contact-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Please fill the form below to contact us",
      },
      {
        id: "contact-name",
        name: "name",
        fieldType: "Input",
        type: "text",
        label: "Name",
        required: true,
        placeholder: "Enter your name",
        width: "md:col-span-3",
      },
      {
        id: "contact-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email",
        required: true,
        placeholder: "Enter your email",
        width: "md:col-span-3",
      },
      {
        id: "contact-message",
        name: "message",
        fieldType: "Textarea",
        label: "Message",
        placeholder: "Enter your message",
        required: true,
      },
      {
        id: "contact-agree",
        name: "agree",
        fieldType: "Checkbox",
        label: "I agree to the terms and conditions",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-multi-step-form",
    title: "Survey Form",
    isMS: true,
    formElements: [
      {
        id: "survey-step-1",
        stepFields: [
          {
            id: "survey-personal-heading",
            name: "heading-2",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Personal Details",
          },
          {
            id: "survey-personal-paragraph",
            name: "paragraph",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Please provide your personal details",
          },
          {
            id: "survey-first-name",
            name: "first-name",
            fieldType: "Input",
            placeholder: "First name",
            label: "First name",
            required: true,
          },
          {
            id: "survey-last-name",
            name: "last-name",
            fieldType: "Input",
            placeholder: "Last name",
            label: "Last name",
          },
        ],
      },
      {
        id: "survey-step-2",
        stepFields: [
          {
            id: "survey-contact-heading",
            name: "heading-2",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Contact Information",
          },
          {
            id: "survey-contact-paragraph",
            name: "paragraph",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Please provide your contact information",
          },
          {
            id: "survey-contact-email",
            name: "your-email",
            fieldType: "Input",
            label: "Your Email",
            type: "email",
            required: true,
            placeholder: "Enter your email",
          },
          {
            id: "survey-contact-phone",
            name: "phone-number",
            fieldType: "Input",
            label: "Phone Number",
            type: "number",
            placeholder: "Enter your phone number",
          },
        ],
      },
      {
        id: "survey-step-3",
        stepFields: [
          {
            name: "step-2",
            id: "survey-preferences-heading",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Your Preferences",
          },
          {
            id: "survey-preferences-toggle",
            name: "preferences",
            fieldType: "ToggleGroup",
            type: "multiple",
            label: "Tell us about your interests and preferences.",
            options: [
              { label: "Technology", value: "technology" },
              { label: "Business", value: "Business" },
              { label: "Health", value: "Health" },
              { label: "Science", value: "Science" },
            ],
          },
          {
            id: "survey-preferences-comment",
            name: "Comment",
            fieldType: "Textarea",
            placeholder: "Share your feedback",
            label: "Feedback Comment",
          },
        ],
      },
    ] as FormStep[],
  } as FormObject,
  {
    id: "template-job-application",
    title: "Job Application",
    isMS: false,
    formElements: [
      {
        id: "job-heading",
        name: "job-application",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Job Application",
      },
      {
        id: "job-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Please fill out the form below to apply for this position",
      },
      {
        id: "job-first-name",
        name: "firstName",
        fieldType: "Input",
        type: "text",
        label: "First Name",
        required: true,
        placeholder: "Enter your first name",
        width: "md:col-span-3",
      },
      {
        id: "job-last-name",
        name: "lastName",
        fieldType: "Input",
        type: "text",
        label: "Last Name",
        required: true,
        placeholder: "Enter your last name",
        width: "md:col-span-3",
      },
      {
        id: "job-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email Address",
        required: true,
        placeholder: "Enter your email address",
      },
      {
        id: "github-url",
        name: "github-url",
        fieldType: "Input",
        type: "url",
        label: "GitHub URL",
        required: false,
        placeholder: "Enter your GitHub URL",
        width: "md:col-span-3",
      },
      {
        id: "linkedin-url",
        name: "linkedin-url",
        fieldType: "Input",
        type: "url",
        label: "LinkedIn URL",
        required: false,
        placeholder: "Enter your LinkedIn URL",
        width: "md:col-span-3",
      },
      {
        id: "job-separator",
        name: "separator",
        fieldType: "Separator",
        static: true,
      },
      {
        id: "job-position",
        name: "position",
        fieldType: "ToggleGroup",
        // placeholder: "Select Position",
        label: "Which position are you applying for?",
        required: true,
        options: [
          { label: "Frontend Developer", value: "frontend" },
          { label: "Backend Developer", value: "backend" },
          { label: "Full Stack Developer", value: "fullstack" },
          { label: "UI/UX Designer", value: "designer" },
          { label: "Product Manager", value: "pm" },
        ],
      },
      [
        {
          id: "job-experience",
          name: "experience",
          fieldType: "Select",
          placeholder: "Select Experience",
          label: "Years of Experience",
          required: true,
          options: [
            { label: "0-1 years", value: "0-1" },
            { label: "2-3 years", value: "2-3" },
            { label: "4-5 years", value: "4-5" },
            { label: "6-10 years", value: "6-10" },
            { label: "10+ years", value: "10+" },
          ],
        },
        {
          id: "job-available-date",
          name: "available-date",
          fieldType: "Select",
          placeholder: "Select Experience",
          label: "When can you start?",
          required: true,
          options: [
            { label: "Within 1 week", value: "next-week" },
            { label: "Within 1 month", value: "next-month" },
            { label: "Within 3 months", value: "next-3-months" },
          ],
        },
      ],
      {
        id: "job-cover-letter",
        name: "cover-letter",
        fieldType: "Textarea",
        label: "Cover Letter",
        placeholder: "Tell us why you're interested in this position...",
      },
      {
        id: "file-upload",
        name: "file-upload",
        fieldType: "FileUpload",
        label: "Attach Resume",
        placeholder: "PDF, DOC or DOCX (max. 5MB)",
        accept: "application/pdf, application/doc, application/docx",
      },
      {
        id: "note",
        name: "note",
        fieldType: "Text",
        variant: "P",
        static: true,
        content:
          "Note: By submitting this form, you agree to our terms and conditions.",
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-job-application-multistep",
    title: "Job Application",
    isMS: true,
    formElements: [
      {
        id: "job-ms-step-1",
        stepFields: [
          {
            id: "job-ms-personal-heading",
            name: "heading-personal",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Personal Information",
          },
          {
            id: "job-ms-personal-paragraph",
            name: "paragraph-personal",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Let's start with your basic information",
          },
          {
            id: "job-ms-first-name",
            name: "firstName",
            fieldType: "Input",
            type: "text",
            label: "First Name",
            required: true,
            placeholder: "Enter your first name",
            width: "md:col-span-3",
          },
          {
            id: "job-ms-last-name",
            name: "lastName",
            fieldType: "Input",
            type: "text",
            label: "Last Name",
            required: true,
            placeholder: "Enter your last name",
            width: "md:col-span-3",
          },
          {
            id: "job-ms-email",
            name: "email",
            fieldType: "Input",
            type: "email",
            label: "Email Address",
            required: true,
            placeholder: "Enter your email address",
          },
          {
            id: "job-ms-phone",
            name: "phone",
            fieldType: "Input",
            type: "tel",
            label: "Phone Number",
            placeholder: "Enter your phone number",
            required: true,
            width: "md:col-span-3",
          },
          {
            id: "job-ms-location",
            name: "location",
            fieldType: "Input",
            type: "text",
            label: "Current Location",
            placeholder: "City, State/Country",
            width: "md:col-span-3",
          },
        ],
      },
      {
        id: "job-ms-step-2",
        stepFields: [
          {
            id: "job-ms-position-heading",
            name: "heading-position",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Position & Experience",
          },
          {
            id: "job-ms-position-paragraph",
            name: "paragraph-position",
            fieldType: "Text",
            variant: "P",
            static: true,
            content:
              "Tell us about the role you're interested in and your experience",
          },
          {
            id: "job-ms-position",
            name: "position",
            fieldType: "ToggleGroup",
            label: "Which position are you applying for?",
            required: true,
            options: [
              { label: "Frontend Developer", value: "frontend" },
              { label: "Backend Developer", value: "backend" },
              { label: "Full Stack Developer", value: "fullstack" },
              { label: "UI/UX Designer", value: "designer" },
              { label: "Product Manager", value: "pm" },
              { label: "DevOps Engineer", value: "devops" },
            ],
          },

          {
            id: "job-ms-experience",
            name: "experience",
            fieldType: "Select",
            placeholder: "Select Experience Level",
            label: "Years of Experience",
            required: true,
            options: [
              { label: "0-1 years (Entry Level)", value: "0-1" },
              { label: "2-3 years (Junior)", value: "2-3" },
              { label: "4-5 years (Mid-Level)", value: "4-5" },
              { label: "6-10 years (Senior)", value: "6-10" },
              { label: "10+ years (Expert)", value: "10+" },
            ],
            width: "md:col-span-3",
          },
          {
            id: "job-ms-available-date",
            name: "availableDate",
            fieldType: "Select",
            placeholder: "Select Availability",
            label: "When can you start?",
            required: true,
            options: [
              { label: "Immediately", value: "immediate" },
              { label: "Within 1 week", value: "1-week" },
              { label: "Within 2 weeks", value: "2-weeks" },
              { label: "Within 1 month", value: "1-month" },
              { label: "Within 3 months", value: "3-months" },
            ],
            width: "md:col-span-3",
          },
          {
            id: "job-ms-salary-expectation",
            name: "salaryExpectation",
            fieldType: "Input",
            type: "text",
            label: "Salary Expectation (Optional)",
            placeholder: "e.g., $80,000 - $100,000 per year",
          },
          {
            id: "job-ms-work-preference",
            name: "workPreference",
            fieldType: "ToggleGroup",
            label: "Work Preference",
            required: true,
            options: [
              { label: "Remote", value: "remote" },
              { label: "On-site", value: "onsite" },
              { label: "Hybrid", value: "hybrid" },
              { label: "Open to all", value: "flexible" },
            ],
          },
        ],
      },
      {
        id: "job-ms-step-3",
        stepFields: [
          {
            id: "job-ms-portfolio-heading",
            name: "heading-portfolio",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Portfolio & Documents",
          },
          {
            id: "job-ms-portfolio-paragraph",
            name: "paragraph-portfolio",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Share your work and upload your documents",
          },

          {
            id: "job-ms-github-url",
            name: "githubUrl",
            fieldType: "Input",
            type: "url",
            label: "GitHub Profile",
            placeholder: "https://github.com/yourusername",
            width: "md:col-span-3",
          },
          {
            id: "job-ms-linkedin-url",
            name: "linkedinUrl",
            fieldType: "Input",
            type: "url",
            label: "LinkedIn Profile",
            placeholder: "https://linkedin.com/in/yourprofile",
            width: "md:col-span-3",
          },
          {
            id: "job-ms-portfolio-url",
            name: "portfolioUrl",
            fieldType: "Input",
            type: "url",
            label: "Portfolio Website",
            placeholder: "https://yourportfolio.com",
            width: "md:col-span-3",
          },
          {
            id: "job-ms-other-url",
            name: "otherUrl",
            fieldType: "Input",
            type: "url",
            label: "Other Profile (Optional)",
            placeholder: "Dribbble, Behance, etc.",
            width: "md:col-span-3",
          },
          {
            id: "job-ms-resume-upload",
            name: "resumeUpload",
            fieldType: "FileUpload",
            label: "Upload Resume/CV",
            placeholder: "PDF, DOC or DOCX (max. 5MB)",
            accept: "application/pdf, application/doc, application/docx",
            required: true,
          },
          {
            id: "job-ms-additional-documents",
            name: "additionalDocuments",
            fieldType: "FileUpload",
            label: "Additional Documents (Optional)",
            placeholder: "Portfolio, certificates, etc. (max. 10MB)",
            accept:
              "application/pdf, image/jpeg, image/png, application/doc, application/docx",
          },
        ],
      },
      {
        id: "job-ms-step-4",
        stepFields: [
          {
            id: "job-ms-final-heading",
            name: "heading-final",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Cover Letter & Final Details",
          },
          {
            id: "job-ms-final-paragraph",
            name: "paragraph-final",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Tell us why you're the perfect fit for this role",
          },
          {
            id: "job-ms-cover-letter",
            name: "coverLetter",
            fieldType: "Textarea",
            label: "Cover Letter",
            placeholder:
              "Tell us why you're interested in this position and what makes you a great fit...",
            required: true,
          },
          {
            id: "job-ms-skills",
            name: "keySkills",
            fieldType: "Textarea",
            label: "Key Skills & Technologies",
            placeholder:
              "List your most relevant skills and technologies (e.g., React, Node.js, Python, AWS...)",
          },
          {
            id: "job-ms-separator",
            fieldType: "Separator",
            label: "Additional Information",
          },
          {
            id: "job-ms-referral",
            name: "referralSource",
            fieldType: "Select",
            label: "How did you hear about this position?",
            placeholder: "Select source",
            options: [
              { label: "Company Website", value: "website" },
              { label: "LinkedIn", value: "linkedin" },
              { label: "Job Board", value: "jobboard" },
              { label: "Employee Referral", value: "referral" },
              { label: "Social Media", value: "social" },
              { label: "Other", value: "other" },
            ],
          },
          {
            id: "job-ms-additional-info",
            name: "additionalInfo",
            fieldType: "Textarea",
            label: "Additional Information (Optional)",
            placeholder: "Anything else you'd like us to know?",
          },
          {
            id: "job-ms-terms-agreement",
            name: "termsAgreement",
            fieldType: "Checkbox",
            label: "I agree to the terms and conditions and privacy policy",
            required: true,
          },
          {
            id: "job-ms-contact-permission",
            name: "contactPermission",
            fieldType: "Checkbox",
            label:
              "I consent to be contacted regarding this application and future opportunities",
            required: true,
          },
        ],
      },
    ] as FormStep[],
  } as FormObject,
  {
    id: "template-event-registration",
    title: "Event Registration",
    isMS: false,
    formElements: [
      {
        id: "event-heading",
        name: "event-registration",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Event Registration",
      },
      {
        id: "event-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Register for our upcoming event",
      },
      {
        id: "event-first-name",
        name: "firstName",
        fieldType: "Input",
        type: "text",
        label: "First Name",
        required: true,
        placeholder: "Enter your first name",
        width: "md:col-span-3"
      },
      {
        id: "event-last-name",
        name: "lastName",
        fieldType: "Input",
        type: "text",
        label: "Last Name",
        required: true,
        placeholder: "Enter your last name",
        width: "md:col-span-3"
      },
      {
        id: "event-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email Address",
        required: true,
        placeholder: "Enter your email address",
      },
      {
        id: "event-company",
        name: "company",
        fieldType: "Input",
        type: "text",
        label: "Company/Organization",
        placeholder: "Enter your company name",
      },
      {
        id: "event-ticket-type",
        name: "ticket-type",
        fieldType: "RadioGroup",
        label: "Ticket Type",
        required: true,
        options: [
          { label: "General Admission - Free", value: "general" },
          { label: "VIP Access - $99", value: "vip" },
          { label: "Premium Package - $199", value: "premium" },
        ],
      },
      {
        id: "event-comments",
        name: "comments",
        fieldType: "Textarea",
        label: "Additional Comments",
        placeholder: "Any special requirements or questions?",
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-product-order",
    title: "Product Order",
    isMS: false,
    formElements: [
      {
        id: "order-heading",
        name: "product-order",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Place Your Order",
      },
      {
        id: "order-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Fill out the details below to complete your order",
      },
      {
        id: "order-product",
        name: "product",
        fieldType: "Select",
        label: "Select Product",
        placeholder: "Select Product",
        required: true,
        options: [
          { label: "Basic Plan - $29/month", value: "basic" },
          { label: "Pro Plan - $59/month", value: "pro" },
          { label: "Enterprise Plan - $99/month", value: "enterprise" },
        ],
      },
      {
        id: "order-first-name",
        name: "firstName",
        fieldType: "Input",
        type: "text",
        label: "First Name",
        required: true,
        placeholder: "Enter your first name",
        width: "md:col-span-3",
      },
      {
        id: "order-last-name",
        name: "lastName",
        fieldType: "Input",
        type: "text",
        label: "Last Name",
        required: true,
        placeholder: "Enter your last name",
        width: "md:col-span-3",
      },
      {
        id: "order-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email Address",
        required: true,
        placeholder: "Enter your email address",
      },
      {
        id: "order-billing-address",
        name: "billing-address",
        fieldType: "Textarea",
        label: "Billing Address",
        required: true,
        placeholder: "Enter your complete billing address",
      },
      {
        id: "order-payment-method",
        name: "payment-method",
        fieldType: "RadioGroup",
        label: "Payment Method",
        required: true,
        options: [
          { label: "Credit Card", value: "credit" },
          { label: "PayPal", value: "paypal" },
          { label: "Bank Transfer", value: "bank" },
        ],
      },
      {
        id: "order-terms",
        name: "terms",
        fieldType: "Checkbox",
        label: "I agree to the terms and conditions",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-customer-support",
    title: "Customer Support",
    isMS: false,
    formElements: [
      {
        id: "support-heading",
        name: "customer-support",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Customer Support Request",
      },
      {
        id: "support-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "We're here to help! Please describe your issue below.",
      },
      {
        id: "support-first-name",
        name: "firstName",
        fieldType: "Input",
        type: "text",
        label: "First Name",
        required: true,
        placeholder: "Enter your first name",
        width: "md:col-span-3",
      },
      {
        id: "support-last-name",
        name: "lastName",
        fieldType: "Input",
        type: "text",
        label: "Last Name",
        required: true,
        placeholder: "Enter your last name",
        width: "md:col-span-3",
      },
      {
        id: "support-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email Address",
        required: true,
        placeholder: "Enter your email address",
      },
      {
        id: "support-order-number",
        name: "order-number",
        fieldType: "Input",
        type: "text",
        label: "Order Number (if applicable)",
        placeholder: "Enter your order number",
      },
      {
        id: "support-category",
        name: "category",
        fieldType: "Select",
        placeholder: "Select Category",
        label: "Issue Category",
        required: true,
        options: [
          { label: "Technical Issue", value: "technical" },
          { label: "Billing Question", value: "billing" },
          { label: "Product Inquiry", value: "product" },
          { label: "Account Access", value: "account" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "support-priority",
        name: "priority",
        fieldType: "RadioGroup",
        label: "Priority Level",
        required: true,
        options: [
          { label: "Low - General inquiry", value: "low" },
          { label: "Medium - Issue affecting usage", value: "medium" },
          { label: "High - Urgent issue", value: "high" },
        ],
      },
      {
        id: "support-description",
        name: "description",
        fieldType: "Textarea",
        label: "Issue Description",
        required: true,
        placeholder: "Please describe your issue in detail...",
      },
    ] as FormElementOrList[],
  } as FormObject,
]


